CREATE TABLE IF NOT EXISTS `tasks` (
    `id` VARCHAR(36) NOT NULL,
    `title` VARCHAR(50) NOT NULL,
    `due_date` DATETIME NOT NULL,
    `status` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `progress` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` DATETIME DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4;
