resources:
  - ../../base
  - ingress.yaml
patches:
  - target:
      kind: ConfigMap
    path: api/configmap.yaml
  - target:
      kind: ConfigMap
    path: flyway/configmap.yaml
helmCharts:
  - name: mysql
    repo: https://charts.bitnami.com/bitnami
    version: 9.8.2
    namespace: sample-bulk-operation-in-ddd
    releaseName: sample-bulk-operation-in-ddd-mysql
    valuesFile: mysql-values.yaml
